package fontlib

func init() {
	register(
		Font{
			Slug:        "spleen-8x16",
			DisplayName: "Spleen 8×16",
			Family:      "Spleen",
			FileName:    "spleen-8x16.woff2",
			Format:      "woff2",
			DesignSizes: []int{16},
			DefaultSize: 16,
			License:     "BSD-2",
			Attribution: "Frederic Cambus <fred@statdns.com>",
			SourceURL:   "https://github.com/fcambus/spleen/releases/download/2.1.0/spleen-2.1.0.tar.bz2",
			InfoURL:     "https://github.com/fcambus/spleen",
			Tags:        []string{"bitmap", "monospace", "receipt"},
			Description: "Monospaced bitmap font designed for clarity at specific pixel sizes. 8×16 is optimal for receipt body text.",
			AutoInstall: false, // tarball requires extraction — use manual install or fonts add
		},
		Font{
			Slug:        "spleen-12x24",
			DisplayName: "Spleen 12×24",
			Family:      "Spleen",
			FileName:    "spleen-12x24.woff2",
			Format:      "woff2",
			DesignSizes: []int{24},
			DefaultSize: 24,
			License:     "BSD-2",
			Attribution: "Frederic Cambus <fred@statdns.com>",
			SourceURL:   "https://github.com/fcambus/spleen/releases/download/2.1.0/spleen-2.1.0.tar.bz2",
			InfoURL:     "https://github.com/fcambus/spleen",
			Tags:        []string{"bitmap", "monospace", "receipt"},
			Description: "Larger Spleen variant. Good for headers or when content density is low.",
			AutoInstall: false, // tarball requires extraction — use manual install or fonts add
		},
		Font{
			Slug:        "press-start-2p",
			DisplayName: "Press Start 2P",
			Family:      "Press Start 2P",
			FileName:    "press-start-2p.ttf",
			Format:      "ttf",
			DesignSizes: []int{8, 16, 24},
			DefaultSize: 16,
			License:     "OFL",
			Attribution: "CodeMan38",
			SourceURL:   "https://fonts.gstatic.com/s/pressstart2p/v16/e3t4euO8T-267oIAQAu6jDQyK0nS.ttf",
			InfoURL:     "https://fonts.google.com/specimen/Press+Start+2P",
			Tags:        []string{"bitmap", "retro", "receipt", "fun"},
			Description: "Classic 8-bit game font. Crisp pixel edges at 8px multiples. Great for retro-styled receipts.",
			AutoInstall: true,
		},
		Font{
			Slug:        "pixel-operator",
			DisplayName: "Pixel Operator",
			Family:      "Pixel Operator",
			FileName:    "pixel-operator.ttf",
			Format:      "ttf",
			DesignSizes: []int{16},
			DefaultSize: 16,
			License:     "OFL",
			Attribution: "Jayvee Enaguas (HarvettFox96)",
			SourceURL:   "",
			InfoURL:     "https://www.dafont.com/pixel-operator.font",
			Tags:        []string{"bitmap", "monospace", "receipt"},
			Description: "Clean pixel font with excellent monospace rendering. Well-suited for receipt body text at 16px.",
			AutoInstall: false,
		},
		Font{
			Slug:        "dogica",
			DisplayName: "Dogica",
			Family:      "Dogica",
			FileName:    "dogica.ttf",
			Format:      "ttf",
			DesignSizes: []int{8},
			DefaultSize: 16,
			License:     "OFL",
			Attribution: "Roberto Mocci",
			SourceURL:   "",
			InfoURL:     "https://www.dafont.com/dogica.font",
			Tags:        []string{"bitmap", "retro", "fun"},
			Description: "Ultra-compact pixel font designed for 8px. Dense, retro game aesthetic.",
			AutoInstall: false,
		},
		Font{
			Slug:        "terminus-16",
			DisplayName: "Terminus 8×16",
			Family:      "Terminus",
			FileName:    "terminus-16.ttf",
			Format:      "ttf",
			DesignSizes: []int{16},
			DefaultSize: 16,
			License:     "OFL",
			Attribution: "Dimitar Zhekov",
			SourceURL:   "https://files.ax86.net/terminus-ttf/files/latest/terminus-ttf-latest.zip",
			InfoURL:     "https://terminus-font.sourceforge.net/",
			Tags:        []string{"bitmap", "monospace", "receipt"},
			Description: "Terminal-style bitmap font. Extremely legible at 16px for body text and data.",
			AutoInstall: false, // zip requires extraction — use manual install or fonts add
		},
	)
}
