package fontlib

func init() {
	register(
		Font{
			Slug:        "vcr-osd-mono",
			DisplayName: "VCR OSD Mono",
			Family:      "VCR OSD Mono",
			FileName:    "vcr-osd-mono.ttf",
			Format:      "ttf",
			DesignSizes: []int{16},
			DefaultSize: 32,
			License:     "Free (personal use)",
			Attribution: "Riciery Leal",
			InfoURL:     "https://www.dafont.com/vcr-osd-mono.font",
			Tags:        []string{"fun", "retro", "monospace"},
			Description: "VHS cassette / TV on-screen display aesthetic. Great for retro receipts.",
			AutoInstall: false,
		},
		Font{
			Slug:        "04b-30",
			DisplayName: "04b_30",
			Family:      "04b_30",
			FileName:    "04b-30.ttf",
			Format:      "ttf",
			DesignSizes: []int{8},
			DefaultSize: 32,
			License:     "Free (personal use)",
			Attribution: "Yuji Oshimoto",
			InfoURL:     "https://www.dafont.com/04b-30.font",
			Tags:        []string{"fun", "retro", "bitmap"},
			Description: "Classic retro LCD pixel font. A staple of early web and game design.",
			AutoInstall: false,
		},
		Font{
			Slug:        "early-gameboy",
			DisplayName: "Early GameBoy",
			Family:      "Early GameBoy",
			FileName:    "early-gameboy.ttf",
			Format:      "ttf",
			DesignSizes: []int{8},
			DefaultSize: 32,
			License:     "Free (personal use)",
			Attribution: "Grand Chaos Font Factory",
			InfoURL:     "https://www.dafont.com/early-gameboy.font",
			Tags:        []string{"fun", "retro", "bitmap"},
			Description: "Faithful recreation of the original Game Boy screen font.",
			AutoInstall: false,
		},
		Font{
			Slug:        "retro-gaming",
			DisplayName: "Retro Gaming",
			Family:      "Retro Gaming",
			FileName:    "retro-gaming.ttf",
			Format:      "ttf",
			DesignSizes: []int{8},
			DefaultSize: 32,
			License:     "Free (personal use)",
			Attribution: "Daymarius",
			InfoURL:     "https://www.dafont.com/retro-gaming.font",
			Tags:        []string{"fun", "retro", "bitmap"},
			Description: "8-bit game console aesthetic. Clean and compact pixel rendering.",
			AutoInstall: false,
		},
		Font{
			Slug:        "kiwi-soda",
			DisplayName: "Kiwi Soda",
			Family:      "Kiwi Soda",
			FileName:    "kiwi-soda.ttf",
			Format:      "ttf",
			DesignSizes: []int{16},
			DefaultSize: 32,
			License:     "OFL",
			Attribution: "Chequered Ink",
			InfoURL:     "https://www.dafont.com/kiwisoda.font",
			Tags:        []string{"fun", "bitmap", "cute"},
			Description: "Cute, bubbly pixel font. Rounded pixel aesthetic good for friendly receipts.",
			AutoInstall: false,
		},
		Font{
			Slug:        "pixellari",
			DisplayName: "Pixellari",
			Family:      "Pixellari",
			FileName:    "pixellari.ttf",
			Format:      "ttf",
			DesignSizes: []int{16},
			DefaultSize: 32,
			License:     "OFL",
			Attribution: "Zacchary Dempsey-Plante",
			InfoURL:     "https://www.dafont.com/pixellari.font",
			Tags:        []string{"bitmap", "clean", "receipt"},
			Description: "Clean, legible 16px pixel font. A versatile choice for receipt body text.",
			AutoInstall: false,
		},
		Font{
			Slug:        "alagard",
			DisplayName: "Alagard",
			Family:      "Alagard",
			FileName:    "alagard.ttf",
			Format:      "ttf",
			DesignSizes: []int{16},
			DefaultSize: 32,
			License:     "Free (personal use)",
			Attribution: "Pix3M",
			InfoURL:     "https://www.dafont.com/alagard.font",
			Tags:        []string{"fun", "fantasy", "bitmap"},
			Description: "RPG fantasy pixel font. Ornate letterforms in a medieval game aesthetic.",
			AutoInstall: false,
		},
		Font{
			Slug:        "minecraft",
			DisplayName: "Minecraft",
			Family:      "Minecraft",
			FileName:    "minecraft.ttf",
			Format:      "ttf",
			DesignSizes: []int{8, 16},
			DefaultSize: 32,
			License:     "Free (personal use)",
			Attribution: "JDGraphics",
			InfoURL:     "https://www.dafont.com/minecraft.font",
			Tags:        []string{"fun", "retro", "bitmap"},
			Description: "Minecraft-style blocky pixel font. Instantly recognizable, great for themed receipts.",
			AutoInstall: false,
		},
		Font{
			Slug:        "upheaval",
			DisplayName: "Upheaval",
			Family:      "Upheaval",
			FileName:    "upheaval.ttf",
			Format:      "ttf",
			DesignSizes: []int{16},
			DefaultSize: 32,
			License:     "Free (personal use)",
			Attribution: "Brian Kent (AEnigma)",
			InfoURL:     "https://www.dafont.com/upheaval.font",
			Tags:        []string{"fun", "bold", "arcade"},
			Description: "Bold arcade-style pixel font. High visual impact for headers and titles.",
			AutoInstall: false,
		},
		Font{
			Slug:        "pixeled",
			DisplayName: "Pixeled",
			Family:      "Pixeled",
			FileName:    "pixeled.ttf",
			Format:      "ttf",
			DesignSizes: []int{10},
			DefaultSize: 32,
			License:     "Free (personal use)",
			Attribution: "OmegaPC777",
			InfoURL:     "https://www.dafont.com/pixeled.font",
			Tags:        []string{"bitmap", "compact", "monospace"},
			Description: "Compact 10px pixel font. Fits more text per line than most bitmap fonts.",
			AutoInstall: false,
		},
	)
}
